### ISSUE TITLE
`fresh init myproject` results in an error

### ISSUE THREAD

**Issue by satyarohith** [freshframework/fresh#21]
```
➜  ~ fresh init tea
error: Uncaught (in promise) TypeError: Must be an absolute path.
  if (!isAbsolute(path)) {
                      ^
    at toFileUrl (https://deno.land/std@0.95.0/path/posix.ts:499:23)
    at routes (file:///Users/sr/c/github.com/lucacasonato/fresh/src/cli/routes.ts:50:20)
    at async init (file:///Users/sr/c/github.com/lucacasonato/fresh/src/cli/init.ts:188:14)
    at async initSubcommand (file:///Users/sr/c/github.com/lucacasonato/fresh/src/cli/init.ts:41:32)
    at async file:///Users/sr/c/github.com/lucacasonato/fresh/cli.ts:34:14
```

The directory `tea` is created and `deployctl run` results in the following error.
```
➜  tea deployctl run --no-check --watch main.ts
error: Cannot resolve module "file:///Users/sr/tea/routes.gen.ts" from "file:///Users/sr/tea/main.ts".
    at file:///Users/sr/tea/main.ts:2:0
```

**Comment by lucacasonato** [comment]
Fixed now (#23)
