### ISSUE TITLE
unable to start project locally

### ISSUE THREAD

**Issue by TheHadiAhmadi** [freshframework/fresh#41]
Hello, 
when I wanted to deploy new project with deployctl There was an error that says: 
```bash
 $ ~/mySrc/myproject deployctl run --watch --no-check **main.ts**
Download https://x.lcas.dev/preact@10.5.12/hooks.js
error: error sending request for url (https://x.lcas.dev/preact@10.5.12/hooks.js): error trying to connect: tls handshake eof
    at https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/deps.ts:2:0
```

versions: 
deno: deno 1.11.4+ed16f43
deployctl: deployctl 0.3.0
fresh: deployctl 0.1.0

Update: 
I don't know why this problem fixed after running deno run main.ts (this command downloaded (https://x.lcas.dev/preact@10.5.12/hooks.js))
then I am able to run deployctl.
but this time after opening the site in browser, deno throws error and 500 response...

```bash
Listening on http://0.0.0.0:8080
 > deno:https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/deps.ts:1:14: error: [plugin: deno] error sending request for url (https://x.lcas.dev/preact@10.5.12/mod.js): error trying to connect: tls handshake eof
    1 │ export * from "https://x.lcas.dev/preact@10.5.12/mod.js";
      ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


 > deno:https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/deps.ts:23:7: error: [plugin: deno] error sending request for url (https://x.lcas.dev/preact@10.5.12/hooks.js): error trying to connect: tls handshake eof
    23 │ } from "https://x.lcas.dev/preact@10.5.12/hooks.js";
       ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: Build failed with 2 errors:
deno:https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/deps.ts:1:14: error: [plugin: deno] error sending request for url (https://x.lcas.dev/preact@10.5.12/mod.js): error trying to connect: tls handshake eof
deno:https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/deps.ts:23:7: error: [plugin: deno] error sending request for url (https://x.lcas.dev/preact@10.5.12/hooks.js): error trying to connect: tls handshake eof
    at failureErrorWithLog (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:3052:19)
    at https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2734:32
    at runOnEndCallbacks (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2532:51)
    at buildResponseToResult (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2732:11)
    at https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2839:18
    at https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2223:13
    at handleIncomingPacket (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2320:13)
    at readFromStdout (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:2190:11)
    at Object.worker.onmessage (https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:3906:38)
    at https://gist.githubusercontent.com/lucacasonato/358c6b7e8198bfb2cf3d220e49fdcf5f/raw/3714cb0f59606eefc29ed0fea36d4cd93549938b/esbuild-wasm.js:3897:45
```

**Comment by lucacasonato** [comment]
@Hadi374 The latest `main` imports preact from a different CDN. That should fix the issue. If you still encounter this, please re-open the issue.
